Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleLogisticSystem.Interfaces;
using SimpleLogisticSystem.Models;
using SimpleLogisticSystem.ViewModels;
using SimpleLogisticSystem.ViewModels.Items;
using SimpleLogisticSystem.ViewModels.Report;
using SimpleLogisticSystem.ViewModels.Warehouses;
using System.Security.Claims;

namespace SimpleLogisticSystem.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IUserRepository _userRepository;
        private readonly IWarehouseRepository _warehouseRepository;

        public ItemController(IItemRepository itemRepository, IHttpContextAccessor httpContextAccessor, IUserRepository userRepository, IWarehouseRepository warehouseRepository)
        {
            _itemRepository = itemRepository;
            _httpContextAccessor = httpContextAccessor;
            _userRepository = userRepository;
            _warehouseRepository = warehouseRepository;
        }

        // GET: /Item/Index
        // Retrieves all items and warehouses from the database and displays them on the index page
        public async Task<IActionResult> Index()
        {
            IEnumerable<Item> items = await _itemRepository.GetAll();
            var itemViewModels = items.Select(item => new ItemViewModel
            {
                Id = item.ItemId,
                ItemName = item.ItemName,
                ItemCategory = item.ItemCategory,
                Weight = item.Weight,
                Price = item.Price,
                Quantity = item.Quantity
            }).ToList();

            IEnumerable<Warehouse> warehouses = await _warehouseRepository.GetAll();
            var warehouseViewModels = warehouses.Select(warehouse => new WarehouseViewModel
            {
                Id = warehouse.Id,
                Name = warehouse.WarehouseName,
                Company = warehouse.WarehouseCompany
            }).ToList();

            var viewModel = new ItemIndexViewModel
            {
                Items = itemViewModels,
                Warehouses = warehouseViewModels
            };

            return View(viewModel);
        }

        // GET: /Item/Create
        // Displays the create item form
        public async Task<IActionResult> Create()
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null) return Unauthorized();

            var currentUser = await _userRepository.GetUserById(userId);
            var createdBy = $"{currentUser.FirstName} {currentUser.LastName}";

            var warehouses = await _warehouseRepository.GetAll();
            var warehouseViewModels = warehouses.Select(warehouse => new WarehouseViewModel
            {
                Id = warehouse.Id,
                Name = warehouse.WarehouseName
            }).ToList();

            var itemVM = new CreateItemViewModel
            {
                CreatedBy = createdBy,
                AppUserId = userId
            };
            return View(itemVM);
        }

        // POST: /Item/Create
        // Handles the submission of the create item form
        [HttpPost]
        public IActionResult Create(CreateItemViewModel itemVM)
        {
            if (ModelState.IsValid)
            {
                var item = new Item()
                {
                    ItemId = itemVM.ItemId,
                    ItemName = itemVM.ItemName,
                    Weight = itemVM.Weight,
                    ItemCategory = itemVM.ItemCategory,
                    Price = itemVM.Price,
                    Quantity = itemVM.Quantity,
                    CreatedBy = itemVM.CreatedBy,
                    AppUserId = itemVM.AppUserId
                };
                _itemRepository.Add(item);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Something went wrong while saving the item. Please try again.");
            }

            return View(itemVM);
        }

        // Get: /Item/Edit/{id}
        // Displays the edit item form for a specific item
        public async Task<IActionResult> Edit(int id)
        {
            var item = await _itemRepository.GetbyIdAsync(id);
            if (item == null) return View("Error");
            var itemVM = new EditItemViewModel
            {
                ItemId = item.ItemId,
                ItemName = item.ItemName,
                ItemCategory = item.ItemCategory,
                Weight = item.Weight,
                Quantity = item.Quantity,
                Price = item.Price,
                CreatedBy = item.CreatedBy,
                AppUserId = item.AppUserId
            };
            return View(itemVM);
        }

        // POST: /Item/Edit/{id}
        // Handles the submission of the edit item form.
        [HttpPost]
        public IActionResult Edit(int id, EditItemViewModel itemVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit warehouse");
                return View("Edit", itemVM);
            }

            var item = new Item
            {
                ItemId = id,
                ItemName = itemVM.ItemName,
                ItemCategory = itemVM.ItemCategory,
                Weight = itemVM.Weight,
                Quantity = itemVM.Quantity,
                Price = itemVM.Price,
                CreatedBy = itemVM.CreatedBy,
                AppUserId = itemVM.AppUserId
            };

            _itemRepository.Update(item);
            return RedirectToAction("Index");
        }

        // POST: /Item/Delete/{id}
        // Handles the deletion of a specific item.
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _itemRepository.GetbyIdAsync(id);
            if (item == null) return View("Error");

            _itemRepository.Delete(item);

            var itemVM = await _itemRepository.GetAll();
            return RedirectToAction("Index");
        }
    }
}

Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleLogisticSystem.Interfaces;
using SimpleLogisticSystem.Models;
using SimpleLogisticSystem.Repository;
using SimpleLogisticSystem.ViewModels.Orders;
using SimpleLogisticSystem.ViewModels.Report;
using SimpleLogisticSystem.ViewModels.Users;
using SimpleLogisticSystem.ViewModels.Warehouses;
using System.Security.Claims;
using System.Text;

namespace SimpleLogisticSystem.Controllers
{
    public class ReportController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly IWarehouseRepository _warehouseRepository;
        private readonly IOrderRepository _orderRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IUserRepository _userRepository;

        public ReportController(IItemRepository itemRepository, IWarehouseRepository warehouseRepository, IOrderRepository orderRepository, IHttpContextAccessor httpContextAccessor, IUserRepository userRepository)
        {
            _itemRepository = itemRepository;
            _warehouseRepository = warehouseRepository;
            _orderRepository = orderRepository;
            _httpContextAccessor = httpContextAccessor;
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        // GET: /Item/InventoryReport
        // Retrieves all items and their warehouse information for the inventory report
        public async Task<IActionResult> InventoryReport()
        {
            var items = await _itemRepository.GetAll();
            var warehouses = await _warehouseRepository.GetAll();
            var warehouseItems = await _warehouseRepository.GetAllWarehouseItems(); // Assuming you have a method to get all WarehouseItems

            var inventoryReportViewModel = items.GroupBy(item => item.ItemName)
                .Select(group => new InventoryReportViewModel
                {
                    ItemName = group.Key,
                    QuantityNotStored = group.Sum(item => item.Quantity),
                    QuantityInWarehouse = group.Sum(item => warehouseItems.Where(wi => group.Any(i => i.ItemId == wi.ItemId)).Sum(wi => wi.Quantity)),
                    WarehouseDetails = warehouseItems
                        .Where(wi => group.Any(item => item.ItemId == wi.ItemId))
                        .Select(wi => new WarehouseDetailViewModel
                        {
                            Warehouse = warehouses.FirstOrDefault(w => w.Id == wi.WarehouseId),
                            TotalQuantity = wi.Quantity,
                            TotalWeight = wi.Weight * wi.Quantity
                        }).ToList()
                }).ToList();

            return View(inventoryReportViewModel);
        }

        // Action to return the warehouse report index view
        public async Task<IActionResult> WarehouseReportIndex()
        {
            IEnumerable<Warehouse> warehouses = await _warehouseRepository.GetAll();
            return View(warehouses);
        }

        // Action to return a detailed report of a specific warehouse
        public async Task<IActionResult> WarehouseReport(int id)
        {
            Warehouse warehouse = await _warehouseRepository.GetbyIdAsync(id);
            if (warehouse == null)
            {
                return NotFound();
            }

            warehouse.WarehouseItems = (await _warehouseRepository.GetWarehouseItemsByWarehouseId(id)).ToList();

            var totalQuantity = warehouse.WarehouseItems.Sum(i => i.Quantity);
            var totalWeight = warehouse.WarehouseItems.Sum(i => i.Weight);

            var viewModel = new WarehouseDetailViewModel
            {
                Warehouse = warehouse,
                TotalQuantity = totalQuantity,
                TotalWeight = totalWeight
            };

            return View(viewModel);
        }

        // Action to return the orders report index view
        public async Task<IActionResult> OrdersReportIndex()
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null) return Unauthorized();

            IEnumerable<Order> orders;

            if (User.IsInRole("admin") || User.IsInRole("inventory_manager"))
            {
                orders = await _orderRepository.GetAllOrdersAsync();
            }
            else
            {
                orders = await _orderRepository.GetOrdersByUserIdAsync(userId);
            }

            var orderViewModels = orders.Select(order => new OrderViewModel
            {
                OrderId = order.OrderId.ToString(),
                OrderType = order.OrderType,
                CreatedBy = order.CreatedBy,
                CreatedAt = order.CreatedAt,
                OrderItems = order.OrderItems,
                OrderStatus = order.OrderStatus,
                Address = order.Address
            }).ToList();

            return View(orderViewModels);
        }

        // Action to return a detailed report of a specific order
        public async Task<IActionResult> OrderReport(string orderId)
        {
            var order = await _orderRepository.GetbyIdAsync(orderId);
            if (order == null)
            {
                return RedirectToAction("OrdersReportIndex");
            }

            return View(order);
        }

        // Action to return a report of all orders
        public async Task<IActionResult> OrderReportAll()
         {
            var orders = await _orderRepository.GetAllOrdersAsync();
            var orderViewModels = orders.Select(order => new OrderViewModel
            {
                OrderId = order.OrderId.ToString(),
                OrderType = order.OrderType,
                CreatedBy = order.CreatedBy,
                CreatedAt = order.CreatedAt,
                OrderItems = order.OrderItems,
                OrderStatus = order.OrderStatus,
                Address = order.Address
            }).ToList();

            return View(orderViewModels);
        }

        // Action to return a report of all user accounts
        public async Task<IActionResult> AccountsReport()
        {
            var users = await _userRepository.GetAllUsers();
            var userViewModels = users.Select(user => new UserViewModel
            {
                Username = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserRole = user.AccountType
            }).ToList();

            return View(userViewModels);
        }

        // Action to export user accounts report to CSV
        [HttpPost]
        public async Task<IActionResult> ExportAccountsToCsv()
        {
            var users = await _userRepository.GetAllUsers();
            var userViewModels = users.Select(user => new UserViewModel
            {
                Username = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserRole = user.AccountType
            }).ToList();

            var csv = new StringBuilder();
            csv.AppendLine("Username,FirstName,LastName,Email,UserRole");

            foreach (var user in userViewModels)
            {
                csv.AppendLine($"{user.Username},{user.FirstName},{user.LastName},{user.Email},{user.UserRole}");
            }

            var bytes = Encoding.UTF8.GetBytes(csv.ToString());
            return File(bytes, "text/csv", "AccountsReport.csv");
        }

        // Action to export a specific order report to CSV
        [HttpPost]
        public async Task<IActionResult> ExportOrderToCsv(string orderId)
        {
            var order = await _orderRepository.GetbyIdAsync(orderId);
            if (order == null)
            {
                return NotFound();
            }

            var csv = new StringBuilder();
            csv.AppendLine("Order ID,Created By,Time of Order,Street,City,Postal Code,Country,Item ID,Item Name,Price,Weight,Quantity");

            foreach (var item in order.OrderItems)
            {
                csv.AppendLine($"{order.OrderId},{order.CreatedBy},{order.CreatedAt},{order.Address.Street},{order.Address.City},{order.Address.PostalCode},{order.Address.Country},{item.Item.ItemId},{item.Item.ItemName},{item.Item.Price},{item.Weight},{item.Quantity}");
            }

            var bytes = Encoding.UTF8.GetBytes(csv.ToString());
            var fileName = $"{orderId}.csv";
            return File(bytes, "text/csv", fileName);
        }

        // Action to export all orders report to CSV
        [HttpPost]
        public async Task<IActionResult> ExportAllOrdersToCsv()
        {
            var orders = await _orderRepository.GetAllOrdersAsync();
            var orderViewModels = orders.Select(order => new OrderViewModel
            {
                OrderId = order.OrderId.ToString(),
                OrderType = order.OrderType,
                CreatedBy = order.CreatedBy,
                CreatedAt = order.CreatedAt,
                OrderItems = order.OrderItems,
                OrderStatus = order.OrderStatus,
                Address = order.Address
            }).ToList();

            var csv = new StringBuilder();
            csv.AppendLine("Order ID,Created By,Created At,Total Price,Total Weight,Items");

            foreach (var order in orderViewModels)
            {
                var items = string.Join(", ", order.OrderItems.Select(item => item.Item.ItemName));
                csv.AppendLine($"{order.OrderId},{order.CreatedBy},{order.CreatedAt},{order.TotalPrice.ToString("C")},{order.TotalWeight.ToString("F2")} Kg,\"{items}\"");
            }

            var bytes = Encoding.UTF8.GetBytes(csv.ToString());
            return File(bytes, "text/csv", "AllOrdersReport.csv");
        }

Views/Shared/_AddToWarehouseDropdown.cshtml
@using SimpleLogisticSystem.ViewModels.Users
@model UserDetailViewModel

<div class="dropdown">
    <button class="btn btn-success dropdown-toggle" type="button" id="addToWarehouseDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Add to Warehouse
    </button>
    <div class="dropdown-menu" aria-labelledby="addToWarehouseDropdown">
        @foreach (var warehouse in Model.Warehouses)
        {
            <a class="dropdown-item" href="#">@warehouse.WarehouseName</a>
        }
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleLogisticSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleLogisticSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleLogisticSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index">Warehouses</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                            </li>
                            @if (User.IsInRole("inventory_manager") || User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Account</a>
                            </li>
                            <li class="nav-item ms-auto">
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button class="btn btn-outline-danger">Logout</button>
                                </form>
                            </li>
                        }
                        else if (!(ViewContext.RouteData.Values["controller"]?.ToString() == "Home" && ViewContext.RouteData.Values["action"]?.ToString() == "Index"))
                        {
                            <li class="nav-item ms-auto">
                                <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-secondary" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>